var n;Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);const aa=Boolean,ba=Array.isArray,t=RegExp.prototype.test,ca=Array.prototype.includes;Array.prototype.concat.bind([]);
const da=Function.call.bind(Array.prototype.slice),ea=Function.apply.bind(Array.prototype.push),u="undefined"==typeof browser;u&&(browser=chrome);const v=navigator.userAgent.includes("Edge/"),fa=navigator.userAgent.includes("Edg/"),y=navigator.userAgent.includes("Firefox/"),ha=navigator.userAgent.includes("OPR/"),ia=navigator.userAgent.includes("YaBrowser/");var z,ja,A,ka,ma,na;
const oa=y?69:v?77:66,pa=y?220:150,F=["127.0.0.1:1001","0.1.0.1:1001"],qa=u?"Chrome_RenderWidgetHostHWND":y?"MozillaWindowClass":v?"Windows.UI.Core.CoreWindow":null,ra=/(?!)/,sa=["main_frame","sub_frame"],ta=["object","image"];var ua=ta.concat("xmlhttprequest",v?"other":[]),va=sa.concat(ta,"xmlhttprequest","other");
const G=["*://*/*"],wa=["ftp://*/*"],xa=G.concat(wa,"file:///*",u?"about:blank":[]),ya=G.concat(u?"about:blank":[]),za=/\.([^.\\/]*?)(?:\.[0-9.]+)?$/,Aa=/^v(\d+)\.(\d+)(?:b(\d+))?\b/,Ba=browser.runtime.getManifest(),Ca=browser.runtime.getURL("captured.html"),Da=browser.runtime.getURL("").slice(0,-1),Ea=browser.extension.getBackgroundPage().location.href,Fa=ha||ia,Ga=u||v;var Ha=!y,Ia=u,Ja=Ba.permissions.includes("notifications")||null;
const Ka=t.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),La=t.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i),Ma=t.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|html|plain))$/),Na=t.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Oa=t.bind(/^idmreg:|\bidman|\binternetdownloadmanager\b/i),Pa=t.bind(/^[GPTSDVACR]*$/),Qa=ca.bind([301,302,303,307,308]),Ra=ca.bind([301,302,303]),Sa=
t.bind(/^(?:https?|socks[45])$/),Ta={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},Ua=[null,[115,111,112,113,114],[111,112,114],[112],[]],Va=[null,[115,116,117,122,118,119,120,121,123],[114,113,113,115,116,117,118,122,119,121,120],[113],[111]],Wa={16:1,17:2,18:4,45:8,46:16},Xa={http:1,https:9,ftp:2,ftps:10,idmreg:12},Ya={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT",
"text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP",
"application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP",
"application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG",
"video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3",
"audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
function H(a,b,c,d,e,f){if(a){var h=["MSG#",a,"#",b,"#",c,"#",d];this.l=a;this.type=b;this.m=c;this.flags=d;this.b=e||[];this.h=h;if(e)for(a=0;a<e.length;a++)h.push(":",e[a]||0);if(f)for(var g in f)if(e=f[g],null!=e)if(h.push(",",g,"="),"string"==typeof e){b=a=e.length;for(c=0;c<b;)d=e.charCodeAt(c++),128<=d&&(2048<=d?(a+=2,d-55296&56320||c++):a++);h.push(a,":",e)}else e instanceof Blob?h.push(e.size,":",e):h.push(e)}else this.j=new FileReader}
function Za(){this.$=this.constructor.prototype.Sa++}Za.prototype.Sa=1;function $a(a,b,c,d){this.id=a;this.port=b;c&&(this.tagName=c=c.toLowerCase(),this.Z="iframe"==c);d&&(this.a=d)}$a.prototype.o=0;function ab(a,b,c){this.id=a+","+b;this.A=0==b;this.b=null==c||0>c?null:a+","+c}function bb(){}function cb(a){a.f||(a.h.push(";"),a.f=!0);return a.h.join("")}function db(a){a.f||(a.h.push(";"),a.f=!0);return new Blob(a.h)}
function eb(a,b,c){a.f?a.c(a):(b.a=c||0,b.b=0,a.j.onload=a.u.bind(a,b),fb(a,b,0,50))}
H.prototype.u=function(a){for(var b=this.j.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.c(this);a.b=1}var f=e.length+1;d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.c(this);this.l=parseInt(d[1]);this.type=parseInt(d[2]);this.m=parseInt(d[3]);this.flags=parseInt(d[4]);b=b.slice(f);a.a+=f;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return fb(this,a,b.length,100);
a.b=4}f=e.length+1;this.b=d=e.split(":");for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(f);a.a+=f;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));d=c.shift().split(":",2);var h=d.shift();f=h.length;e=!1;if(d.length)f++;else{if(!c.length)return fb(this,a,b.length,25);e=!0}d=h.split("=",3);if(2!=d.length)return this.c(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[c]=d;b=b.slice(f);a.b++;break}a.c=c;a.count=d;b=a.count;f=a.a;
a=a.slice(f,f+b);a.size==b?this.j.readAsText(a):this.c(this);return;case 3:return this[a.c]=b,a.a+=a.count,a.b++,fb(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.c(this)}a.a++;break;case 5:this.f=!0;this.g(this);a.size>a.a&&(b=new H,b.g=this.g,b.c=this.c,eb(b,a,a.a));return}};function fb(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.j.readAsBinaryString(b.slice(e,c+d)):a.c(a)}
function I(){if(z){var a=this.constructor.prototype;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.Ra=[];this.va=!1;this.wa=this.da=null;this.u=!1;this.ka=0;this.sa=null;this.c={};this.h={};this.a={};this.G={};this.b={};this.I={};this.f={};this.g={};this.ja={};this.ga={};this.ha={};this.ha.jc=[];this.Ya=0;this.j=this.Pa=!1;this.za=!0;this.M=null;this.Ta=this.Xa=!1;this.zb=this.Wa=this.xb=1;this.ia={};this.l=null;this.xa=1;this.$a=0;this.H=this.D=null;this.Ua=ra;this.W=
[null,{},{},{},{}];this.ca=this.m=null;this.la=Array(16);this.ua=0;this.Va=null;this.ya=this.ta=!1;for(a=1;a<Ua.length;a++){var b=this.W[a];for(var c of Ua[a])b[c]=ra}u&&browser.browserAction.disable();y&&browser.runtime.onInstalled.addListener(this.Fb);browser.runtime.onMessage.addListener(this.Gb);browser.windows.onCreated.addListener(this.nb);browser.windows.onRemoved.addListener(this.ob);browser.windows.onFocusChanged.addListener(this.ec);browser.tabs.onActivated.addListener(this.Wb);browser.tabs.onUpdated.addListener(this.Zb);
browser.tabs.onRemoved.addListener(this.Yb);browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.Xb);this.Na();this.Ca();gb(this,!0)}}n=I.prototype;n.Fb=function(a){a.version=Ba.version;this.wb=a};n.Gb=function(a,b){38==a[0]&&browser.tabs.remove(b.tab.id)};
n.lb=function(a){browser.runtime.lastError;if(a){var b=a.value;a=Ta[b.mode];var c,d;this.la.fill(void 0);if(5==a&&(d=b.pacScript))d.data&&5E4<d.data.length?a=4:(c=d.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=d.url,this.la.fill(!0);else if(7==a){b=b.rules;d=b.bypassList;c=J(this,b.singleProxy);if(!c){c=J(this,b.fallbackProxy);var e=J(this,b.proxyForHttp,1),f=J(this,b.proxyForHttps,9);b=J(this,b.proxyForFtp,2);e!=f||e!=b||e!=c&&c?(c=(e||"")+";"+(f||"")+
";"+(b||"")+";"+(c||""),++a):c=e}d&&d.length&&(c+=";"+d.join(","))}b=5>a?a.toString():c?a+":"+c:null;b!=this.m&&(this.m&&this.Aa(),this.m=b)}};function J(a,b,c){if(b){var d=b.scheme||"http",e="https"==d;a=a.la;c?a[c]=e:a.fill(e);if(Sa(d))return d+"://"+b.host+(b.port?":"+b.port:"")}}
function hb(a,b,c,d){if(b){var e=b.type;if("direct"==e)return"0";"socks"==e&&(e="socks5");if(Sa(e)){var f="1:"+e+"://"+b.host+":"+b.port;"socks5"==e&&b.proxyDNS&&(f+="#");c||d||!(c=a.ca)||(c=c.substr(c.indexOf(";")+1||c.length));c&&(f+=";"+c);d&&f&&(a.ca=f);return f}}}
n.Aa=function ib(a,b){if(void 0===a){if((Ha||Ia)&&this.u){var d=this.D;d||(b="http://"+(this.da?(new URL(this.da.url)).host:F[0]),d=b+"/status/204+IDM");a=new XMLHttpRequest;a.timeout=1E3;a.onreadystatechange=ib.bind(this,a,b);a.open("GET",d,!0);a.send()}}else 4==a.readyState&&(204!=a.status?this.D=this.H=null:b&&(this.D=b+"/status/204+IDM",this.H=Ha&&this.sa?b+"/client/"+this.sa:null))};
function gb(a,b){var c=a.c,d=a.ia={};browser.contextMenus.removeAll();for(var e=0;e<jb.length;e++){var f=jb[e];if(f[0]&&(y?b||c[f[1]]:1)){var h=f[3].split(","),g;u&&1392508928<=z&&1409286144>z&&0<=(g=h.indexOf("frame"))&&h.splice(g,1);d[e]=browser.contextMenus.create({title:kb(f[2]),contexts:h,onclick:f[4].bind(a),documentUrlPatterns:f[5]||xa,enabled:!0})}}}n.ra=function(a,b,c,d){var e=this.f;return b in e?e[b]:e[b]=new $a(b,a,c,d)};
function lb(a,b){a=a.g;var c=b.id;a[c]!==b&&(a[c]=b,v&&(a[b.requestId]=b))}function mb(a,b,c,d,e){a=a.G;if(K(b)){var f=b.frameId||0;var h=b.parentFrameId;d||(d=b.tabId);e||b.requestId||(e=b.url)}else f=b;b=d+","+f;d=a[b]||(a[b]=new ab(d,f,h));null!=c&&(d.f=c);e&&"about:blank"!=e&&(d.i=e);return d}function L(a,b){return a.G[b.tabId+","+b.frameId]}function nb(a){var b=new Za;return a.I[b.$]=b}function rb(a,b){var c=b instanceof Za&&b.$,d=c?b:a.I[b];delete a.I[c||b];return d}
function sb(a,b){a=a.W;for(var c=1;c<a.length;c++){var d=a[c][101];if(d&&d.test(b))return c}return 0}
n.Ca=function(){var a=this.ka%(F.length+1);if(a<F.length)this.da=a=new WebSocket("ws://"+F[a]+"/?cid="+Math.random().toString().substr(2,9),"plugin.v3.internetdownloadmanager.com"),a.onopen=this.Ia,a.onclose=this.R,a.onmessage=this.Vb,1==a.readyState?this.Ia():3==a.readyState&&this.R();else{this.wa=a=browser.runtime.connectNative("com.tonec.idm");try{a.postMessage("")}catch(b){a=null}a?(a.onDisconnect.addListener(this.R),a.onMessage.addListener(this.Jb),this.Ia()):this.R()}};
n.Ia=function(){this.u=!0;this.Wa=1;var a=browser.i18n.getUILanguage().replace("_","-");"sr"==a&&(a+="-Cyrl-CS");var b=[14,38,Fa?1028:1031,0],c={};c[112]=A;c[113]=ja;c[114]=qa;c[125]=JSON.stringify(this.wb);c[116]=a;M(this,2,1,Fa?0:1024,b,c)};
n.R=function(){browser.runtime.lastError;this.da=this.wa=null;if(this.u){this.u=!1;this.ja={};for(var a=this.Ra,b=0;b<a.length;b++){var c=a.splice(b--,1).pop(),d=c.splice(0,2).pop();v&&c.splice(1);d.removeListener.apply(d,c)}this.va=!1;this.m=this.H=this.D=null;u&&browser.browserAction.disable();u&&this.j&&browser.downloads.setShelfEnabled(!0)}a=++this.ka;b=F.length+1;c=a/b;120>c&&(1==c&&this.za&&this.Ba(),!a||a%b?this.Ca():window.setTimeout(this.Ca,5E3*c))};
n.Vb=function(a){var b=new H;b.g=this.jb;b.c=this.R;eb(b,a.data)};n.Jb=function(a){var b=new H;b.g=this.jb;b.c=this.R;eb(b,new Blob([a]))};function M(a,b,c,d,e,f,h){if(!a.u)return!1;var g=a.Wa++;b=new H(g,b,c,d,e,f);if(h)return h.open("POST",a.H+"?seq="+g,!1),h.send(db(b)),200==h.status;if(h=a.da)h.send(db(b));else try{a.wa.postMessage(cb(b))}catch(l){return a.R(),!1}d&1&&(a.ja[g]=b);return!0}
function tb(a,b){if(b.b){var c=b.b[6],d=a.g[c];if(d)return d.N?b.a=d.port.id:null;d=a.h;for(var e in d)if(d[e].c==c)return b.a=e}e=b[6];d=b[17];var f=b[50],h=b[7],g=a.ha,l=a.f;a=a.a;var k;if((k=g[e])||(k=g[d]))return b.a=k.id;if(k=g[f])var m=k.id;for(c in l){g=l[c];var p=g.a;if(p){if(p==e||p==d||p==f){k=g.port;if(h){var q=a[k.tabId];q&&q.i!=h&&(k=null)}if(k)return b.a=k.id}if(p==h)var r=g.port.id}}return m?b.a=m:r?b.a=r:null}
n.bb=function ub(a,b,c,d){if(b)return browser.runtime.lastError,d?(b=(c=d.shift())&&this.a[c.id])?a.a=b.id:null:null;if(null!=a.a)return a.a;if(a.b){var f=a.b[7];if(f&&this.h[f])return a.a=f}if(tb(this,a))return a.a;d=this.h;var h=a[50],g=a[7];for(f in d){b=d[f];if(b.i==h){a.a=f;break}b.i==g&&(a.a=f)}if(null!=a.a)return a.a;g&&browser.tabs.query({url:g},ub.bind(this,a,!0,c));return null};
n.Fa=function vb(a,b,c){var e=a.tabId,f=a.Y;if(b)if(ba(c))for(var h=a.i,g=h.includes("#")&&N(h),l=c.length;l--;){b=c[l];var k=b.frameId;if(k!=f)if(k&&!b.vc&&(b.url==h||g&&b.url==g))f=a.Y=k;else continue;var m=b.parentFrameId;break}else c?m=c.parentFrameId:browser.runtime.lastError;else if(0<f?!a.f:null==f){if(f&&822083584<=z)return browser.webNavigation.getFrame({frameId:f,tabId:e},vb.bind(this,a,!0));if(f||a.i)return browser.webNavigation.getAllFrames({tabId:e},vb.bind(this,a,!0))}0<=m&&(a.f=e+","+
m);if(null!=f&&a.g){c=e+","+f;if(b=this.G[c])a.c=b.c,a.B=b.B,a.b=b.f,(m=b.S)&&a.i!=m&&(a.S=m),a.f||(a.f=b.b),(b=this.g[a.c])&&!b.port&&(b.port=a);this.a[c]=a;e=[11,e,f,a.b,a.B];(f=a.j)&&a.B&&(b=this.W[f],c=Va[f],e.push(f),ea(e,c.map(wb(b)).map(xb)));a.postMessage(e)}};
n.fa=function yb(a,b,c,d,e,f,h,g){var k=zb(a,!0);if(!k)return 0;if(1==k){if(!h)return O(a,yb.bind(this,a,b,c,d,e,f,!0)),-1;K(g)&&(g=P(g))}h=[k];var m={};m[6]=N(a,1==k);m[50]=b;m[7]=c;m[8]=d;m[100]=e;m[102]=f;m[51]=g;m[54]=navigator.userAgent;m[121]=y?this.ca:this.m;M(this,14,1,0,h,m);return 3};
n.tb=function(a,b,c,d,e){if(!d){if(!a||!a.length)return;c||(c={});var f=new Q(this,a,b,c,!0);c.pageUrl&&!c.rb&&O(c.pageUrl,R(f,4));for(var h=0;h<a.length;h++)O(a[h][0],R(f,5+h));if(f.wait())return}e&&(c.rb=P(e));for(h=0;h<a.length;h++)a[h][5]=P(arguments[h+5]);f=0;h=[0];var g={8:4};g[54]=navigator.userAgent;g[7]=c.pageUrl;g[110]=c.hc;g[111]=c.rb;g[121]=y?this.ca:this.m;1<a.length&&(M(this,15,1,0,[a.length],g),f=16,g={});for(var l;l=a.shift();)g[6]=l[0],g[100]=l[2],g[102]=l[3],g[50]=l[4],g[51]=l[5],
M(this,14,1,f,h,g)};function Ab(a,b,c,d,e,f,h,g){if(!d||a.c[-8]){var l=a.a[b];if(l){var k=nb(a),m=k.$;k.tabId=b;k.port=l;k.selection=c;k.count=0;k.Za=[];if(l=d&&!!e)k.kc=!0,k.wc=e,k.clientX=f,k.clientY=h,k.zoom=g,e.A||Bb(a,e);(d=d&&a.c[12])?(d=d.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),d="^(?:http|https|ftp|ftps)://(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)"):d="^(?:http|https|ftp|ftps)://";k.cb=Cb(a,b,[12,m,c,l,d]);k.Ab=0;k.cb||rb(a,m)}}}
n.ic=function(a,b,c,d,e,f,h,g){if(a=this.I[b]){d&&(a.count+=d);h&&(a.pageUrl=h);g&&(a.hc=g);if(e&&("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array)){if(f)for(var l of e)l[4]=f;ea(a.Za,e)}++a.Ab==a.cb&&(rb(this,a),a.kc?(d=a.tabId,(e=this.b[a.port.a])&&e.s==d&&a.count&&(f=a.zoom,h=e.c,g=e.a,M(this,10,1,0,[4294967295,e.I,Math.round(a.clientX*f+(e.g+h)*g),Math.round(a.clientY*f+(e.H+h)*g),0,a.count]),this.l=d,Cb(this,d,[13,!0]))):(d=a.Za,d.length?this.tb(d,a.selection,a):Db(a.tabId,"cannot_find_links")))}};
n.Nb=function(a,b,c,d){(a=rb(this,b))&&this.fa(a.linkUrl,a.Ka,a.pageUrl,a.flags,c,d)};n.Qb=function(a,b,c,d,e){this.ra(a,b,c,d);a=[b,a.tabId,a.c,a.j];b={};b[132]=d;b[133]=e;M(this,23,1,0,a,b)};n.J=function(a,b,c){if(4294967295==a)this.l=null,c=!0;else{var d=this.f[a];if(d){c=d.o;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.o=3;window.setTimeout(this.J.bind(this,a,!1,!0),1E3);return}d.o=0;c=!0}}c&&M(this,8,1,32,[a])};
n.pc=function(a,b,c,d,e,f,h,g){var l=a.tabId,k=a.a,m=this.b[k];if(b){if(b=rb(this,b)){var p;if(!c||null==e){if(!a.A){c=a.na;f="iframe";h=a.i;var q=!!c}if(!q){c=l;f=h=null;var r=!0}}!g&&(p=this.a[l])&&(g=p.title);a=this.ra(a,c,f,h);q=(m=l==m.s&&!m.C&&(r||q||e))&&!a.o;a.o=m?1:2;b instanceof H&&S(this,b,2,(m?128:64)|(r?512:0),k,l,c,g);r||(Eb(this,c,e),q&&window.setTimeout(this.aa.bind(this,k),3E3))}}else d?(this.J(c,!0),delete this.f[c]):l!=m.s||m.C||(e?Eb(this,c,e,!0):Fb(this,c))};
function Gb(a,b){var c=a.b[b];if(c&&c.b){var d=c.c,e=c.a;M(a,7,2,c.C?128:c.l?256:c.f?512:0,[b,Math.round((c.g+d)*e),Math.round((c.H+d)*e),Math.round((c.width-d-c.u)*e),Math.round((c.height-d)*e)])}}
function Eb(a,b,c,d){var e=a.f[b];if(e&&e.o){var f=e.port,h,g=256;2==e.o&&(null==d&&(h=a.b[f.a])&&(d=f.tabId==h.s&&!h.C),d?(g|=128,e.o=1):g|=64);(d=e.Z)&&!c&&(c=f.h);if(c){var l=c[0];var k=c[1];var m=c[2]||l+1;var p=c[3]||k+1;var q=c[4];if(c=!d&&f.h)l+=c[0],k+=c[1],m=Math.min(m+c[0],c[2]),p=Math.min(p+c[1],c[3]);if(f=a.a[f.tabId])var r=f.l}M(a,9,1,g,[b,l,k,m,p,q,r])}}
n.aa=function(a){var b=[],c={};if(a){var d=this.b[a];d&&(d.C||d.L||b.push(d.s))}else for(d of T(this.b))d.C||d.L||b.push(d.s);if(b.length)for(var e of T(this.f))a=e.port,e.o&&b.includes(a.tabId)&&((d=this.a[a.tabId])&&d.update&&(d.update=!1,d.postMessage([14,!1])),e.tagName?a.A?a.postMessage([15,null,e.id]):Bb(this,a,null,c):Eb(this,e.id,null,!0))};function Hb(a,b){(b=a.b[b])&&!b.L&&Ib(a,b.s,void 0)}
function Ib(a,b,c){var d=c?0:2;c=c?32:64;var e=a.f,f;for(f in e){var h=e[f];h.o&&h.port.tabId==b&&h.o!=d&&(h.o=d,M(a,8,1,c,[f]))}}function Fb(a,b){var c=a.f[b];c&&1==c.o&&(c.o=2,M(a,8,1,64,[b]))}function Jb(a,b,c,d){var e=a.ua,f=(e&b)!=((c?63:32)&b);a.ua=c?e|=b:e&=~b;f&&(c=a.c[-1],b=a.c[-2],c=a.ta=0!=c&&(e&c)==c,e=a.ya=0!=b&&(e&b)==b,a.Va=(c||e)&&d||null)}
n.Ma=function Kb(a,b,c,d){var f=this.b[a];if(f)if(d)f.h|=b,f.j|=c,f.L&&window.clearTimeout(f.L),f.L=window.setTimeout(Kb.bind(this,a),d);else{b|=f.h;c|=f.j;f.h=f.j=f.L=null;if(b){for(var h in this.h)b=this.h[h],b.a==a&&b.A&&(b.update=!0);browser.windows.get(a,this.V);browser.tabs.query({windowId:a,active:!0},this.V)}if(c){if((a=this.b[a])&&!a.L){a=a.s;c=this.f;for(var g in c)h=c[g],h.o&&h.port.tabId==a&&1==h.o&&M(this,8,1,1152,[g])}}else this.aa(a)}};
n.V=function(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,d=this.b[c];if(d){if(a.windowId){if(d.m&&Ka(a.url))return;d.s=a.id;a.width&&(d.G=a.width);a.height&&(d.D=a.height)}else{var e=b?d.a=this.xa:d.a,f="fullscreen"==a.state,h=!b&&f!=d.C;d.C=f;d.l="maximized"==a.state;d.f="minimized"==a.state;v?(d.width=Math.round(a.width/e),d.height=Math.round(a.height/e),d.left=Math.round(a.left/e),d.top=Math.round(a.top/e)):(d.width=a.width,d.height=a.height,d.left=
a.left,d.top=a.top);h&&(f?Hb(this,c):this.aa(c))}f=d.G;a=d.D;if(f&&a){h=d.width;e=d.height;if(!d.m&&!d.f){if(f>h||a>e)return browser.windows.get(c,this.V);d.m=!0}f=h-f;h=f/2;0<=h&&20>=h?(d.c=h,d.g=d.u=0):(h=d.c,y||ha?d.g=f-2*h:d.u=f-2*h);a=e-a-2*h;a<=pa&&50<=a&&(d.H=a)}b||Gb(this,c);return d}}};n.mc=function(a,b,c,d){a.i=b;a.Ka=c;a.b&&!d&&(a.b=!1);null==a.Y&&this.Fa(a);this.aa(a.a)};n.oc=function(a,b,c,d){a.title=b;a.l=d;a=[a.c,a.tabId,a.a,c,d];c={};c[110]=b;M(this,21,1,0,a,c)};
n.qc=function(a,b,c,d,e){if(b=this.a[a.tabId+","+c]){b.na=d;if(b.h=e)if(a=a.h)e[0]+=a[0],e[1]+=a[1],e[2]=Math.min(e[2]+a[0],a[2]),e[3]=Math.min(e[3]+a[1],a[3]);Eb(this,d,e);for(var f of T(this.f))f.port==b&&f.o&&f.tagName&&!f.Z&&b.postMessage([15,null,f.id])}};function Bb(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.f];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.na,c[2]=b.Y,c[3]=d,c[4]=d?null:b.i,c[5]=d?null:b.S,f.postMessage(c)}
function Cb(a,b,c){a=a.a;b+=",";var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}n.oa=function(a,b){var c={file:"content.js",runAt:"document_start",allFrames:!0,matchAboutBlank:!0};!v&&b&&(c.frameId=b,y&&(c.allFrames=!1));if(a instanceof Array)for(;b=a.shift();)try{b.discarded||browser.tabs.executeScript(b.id,c,W)}catch(d){}else if(b=a)try{browser.tabs.executeScript(b.id||b,c,W)}catch(d){}};
function Lb(a,b,c,d){var e=17,f=[b.I,b.b,b.width,b.height,b.left,b.top,b.a],h={};b.l?e|=256:b.f&&(e|=512);null!=c&&(e|=c?2048:1024);d&&(h[117]=d);M(a,6,2,e,f,h)}n.Na=function Mb(a,b){if(b)for(;b.length;){a=b.shift();var d=this.V(a,!0)||this.nb(a,!0);Lb(this,d,a.focused,a.title)}else if(!a){b=Mb.bind(this,!0);try{browser.windows.getAll({windowTypes:["normal","popup"]},b)}catch(e){browser.windows.getAll(b)}}};
n.ub=function Nb(a,b){if(void 0===a)return Ob("system.display",Nb.bind(this));if(a){if(!b)return browser.system.display.getInfo(null,Nb.bind(this,a));this.$a=b[0].displayZoomFactor}};
n.Da=function(a,b){if(!this.u)return Db(b.id,"cannot_contact_idm");var c=a.linkUrl,d=a.pageUrl,e=d;if(a.menuItemId==this.ia[4])return browser.downloads.search({query:[c]},this.yb.bind(this,c));if(a.menuItemId==this.ia[1])c=a.frameUrl,c&&"about:blank"!=c||(c=d,e=null);else if(!c&&(c=a.srcUrl,a=this.a[b.id+","+a.frameId])){var f=nb(this);f.tabId=b.id;f.port=a;f.linkUrl=c;f.Ka=e;f.pageUrl=d;f.flags=4;return a.postMessage([18,f.$,c])}c&&this.fa(c,e,d,4)};
n.ab=function(a,b){if(!this.u)return Db(b.id,"cannot_contact_idm");Ab(this,b.id,a.menuItemId==this.ia[2])};n.yb=function(a,b){for(var c,d,e;c=b.pop();)c.exists&&"complete"==c.state?d||e||(e=c.referrer):(d||(d=c.referrer),browser.downloads.erase({id:c.id}));this.fa(a,d||e,null,4)};
n.Rb=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=this.xb++);var d=b.id,e="top"==a.name;a.tabId=d;a.a=0>b.index?null:b.windowId;a.g=!0;a.loaded=!1;a.update=e;a.A=e;a.Y=e?0:a.sender.frameId;a.m=0;a.i=a.sender.url||e&&b.url||null;a.S=null;this.h[c]=a;e&&(this.a[d]=a);a.i&&(a.j=sb(this,(new URL(a.i)).hostname));a.onMessage.addListener(this.Sb.bind(this,a));a.onDisconnect.addListener(this.pa);this.Fa(a)}};
n.pa=function(a,b){browser.runtime.lastError;if(a.g){a.g=!1;var c=a.tabId+","+a.Y,d=this.I,e=this.f,f,h=this.ha,g=this.g,l,k;for(k in d)d[k].port===a&&delete d[k];for(k in e)if(f=e[k],f.port===a)this.J(k),delete e[k];for(var m in h)h[m]===a&&delete h[m];for(k in g)(l=g[k],l.port!==a||l.B)||(delete g[k],v&&delete g[l.id]);this.Va===a&&Jb(this,63,!1);delete this.h[a.id];delete this.a[c];a.A&&delete this.a[a.tabId];if(v&&!b)browser.tabs.executeScript(a.tabId,{code:"__idm_connect__ && __idm_connect__(); true;"},
W);else for(k in a=this.G,a)c==a[k].b&&delete a[k]}};
n.Sb=function(a,b){var c=b[0];b[0]=a;switch(c){case 21:this.mc.apply(this,b);break;case 24:this.oc.apply(this,b);break;case 22:this.qc.apply(this,b);break;case 23:this.pc.apply(this,b);break;case 41:this.Qb.apply(this,b);break;case 25:this.ra.apply(this,b);break;case 26:Ab(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:this.ic.apply(this,b);break;case 28:this.J(4294967295);break;case 29:this.ib.apply(this,b);break;case 30:this.ib.apply(this,b);break;case 31:this.Lb.apply(this,b);break;case 32:this.Ob.apply(this,
b);break;case 39:this.Mb.apply(this,b);break;case 33:this.Hb.apply(this,b);break;case 34:this.Kb.apply(this,b);break;case 35:this.Nb.apply(this,b);break;case 36:this.fc.apply(this,b);break;case 37:this.Ub.apply(this,b)}};
n.jb=function(a){var b=a.type,c=a.m,d=a.flags,e=a.b,f;if(1==b){var h=e[0];if(f=this.ja[h])b=f.type,delete this.ja[h]}switch(b){case 3:0<=this.ka&&(this.ka=-1,this.Aa());d=e[0];this.Xa=9>d;this.Ta=10<=d;this.sa=e[6];if(d=e[4])d/=96,this.xa=u&&1.245>d?1:d,this.Na(),u&&this.$a&&this.ub();Pb(this,e[5],a);this.za&&this.Ba();break;case 4:f=this.c;this.j=!!(e[3]&2147483648);Pb(this,e[2],a);f[-9]=0<(d&64);f[-13]=0<(d&1024)||Fa;f[-8]=0<(d&32);f[-4]=0<(d&2);f[-11]=0<(d&256)||2>c;f[-12]=0<(d&512)||2>c;f[-1]=
e[0];f[-2]=e[1];f[12]=a[12];f[17]=a[17];X(f,a,1);X(f,a,2);X(f,a,3);X(f,a,4);X(f,a,10);X(f,a,9,2);X(f,a,11,2);X(f,a,20);X(f,a,21,1);Qb(f,a,19);Qb(f,a,18,1,1);gb(this);this.va||(this.va=!0,u&&browser.browserAction.enable(),this.v(1,browser.runtime.onConnect,this.Rb),this.v(1,browser.webNavigation.onCreatedNavigationTarget,this.Pb),this.v(1,browser.webNavigation.onCommitted,this.kb),this.v(1,browser.webNavigation.onHistoryStateUpdated,this.Ib),u&&this.v(1,browser.proxy.settings.onChange,this.lb),u&&
browser.proxy.settings.get({},this.lb),u&&this.j&&browser.downloads.setShelfEnabled(!1),u&&this.j&&this.v(2,browser.downloads.onCreated,this.Db),u&&this.j&&this.v(2,browser.downloads.onDeterminingFilename,this.Eb),e=ma?void 0:va,a=["blocking"],d=u&&!na&&1207959552<=z?["extraHeaders"]:[],this.v(3,browser.webRequest.onBeforeRequest,this.mb,{urls:wa,types:sa},a),this.v(3,browser.webRequest.onBeforeRequest,this.mb,{urls:G,types:e},["requestBody"]),this.v(3,browser.webRequest.onBeforeSendHeaders,this.ac,
{urls:G,types:e},["requestHeaders"].concat(a,d)),this.v(3,browser.webRequest.onHeadersReceived,this.cc,{urls:G,types:e},["responseHeaders"].concat(a)),this.v(3,browser.webRequest.onResponseStarted,this.dc,{urls:G,types:e}),this.v(3,browser.webRequest.onErrorOccurred,this.bc,{urls:G,types:e}),(e=this.c[17])&&this.v(4,browser.webRequest.onBeforeRequest,this.$b,{urls:e.split("|"),types:sa},a),browser.tabs.query({url:G},this.oa));break;case 18:d=e[0];if(4<=d)break;e=Ua[d];d=this.W[d];for(var g in a)(g=
parseInt(g))&&(102==g||110<g&&150>g)&&(d[g]=e.includes(g)?RegExp(a[g]):a[g]);e=this.W.map(Rb(102)).filter(aa);this.Ua=RegExp("^https?://(?:"+e.join("|")+")","i");X(d,a,101,2);break;case 5:a=e[0];(e=this.b[a])?(d=0!=(d&128),e.C!=d&&(e.C=d)&&Hb(this,a)):this.ob(a);break;case 6:if(d&4)break;a=f.b[0];e=e[1];if(d=this.b[a])d.b=e,Gb(this,a);break;case 8:a=e[0];e=d&32;if(4294967295==a)Cb(this,this.l,[13,!1]),this.l=null;else if(a=this.f[a])a.o=e?0:2;break;case 11:a=e[0];4294967295==a&&(Ab(this,this.l,!0,
!0),this.l=null);break;case 12:try{var l=a.b[5],k=a[4];e=4==l?2:3;if((1==l||2==l)&&tb(this,a)){if(this.c[3].test(k))1==l?e=6:l=4;else if(this.c[-4]||this.c[4].test(k))e=6;a[8]|=256}if(4==l)if(this.Xa&&!a.b[7])S(this,a,1);else{switch(a.b[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.sb(a)}else S(this,a,e)}catch(m){S(this,a,0)}break;case 13:a=f.b[0];d=f.b[5];e=e[1];g=3==e;if(3>=d)f.flags&128?Sb(this,a,g):Y(this,a,g);else if(5==d)if(e){if(a=(f=this.g[a])&&f.ea){g=
f.method;e=f.requestHeaders;if(d=f.U)(d=Tb(d,Z(e,"Content-Type")))||(g="GET");a.timeout=1E4;a.onreadystatechange=this.Tb.bind(this,a,f.id);a.open(g,f.url,!0);for(f=0;f<e.length;f++)g=e[f].name,c=g.toLowerCase(),c.startsWith("x-idm-")||(La(c)&&(g="X-IDM-"+g),a.setRequestHeader(g,e[f].value));a.send(d)}}else Ub(this,a);break;case 20:e=a[123];d=!e;a=[a.l,0,0,0];f={};y&&(g=this.ca)&&(f[122]=g,d||(d=g.substr(2).split(";",1).shift()==e));f[121]=this.m;M(this,1,1,d?2:4,a,f);break;case 22:this.Qa(e[0],e[1],
a[131],a[130]);break;case 1:break;default:!f&&d&1&&M(this,1,1,0,[a.l,0,0,0])}};n.Qa=function Vb(a,b,c,d,e){if(!v&&null==Ja){if(void 0===e)return Ob("notifications",Vb.bind(this,a,b,c,d));Ja=e||!1}Ja&&(browser.notifications.create(a.toString(),{type:"basic",title:d||"",message:c,iconUrl:"images/logoSmall.png"},W),b&&window.setTimeout(browser.notifications.clear.bind(null,a.toString(),W),1E3*b))};
n.sb=function(a,b,c){try{if(null==a.a)if(!b){var d=new Q(this,a,!0);this.bb(a,null,d)||browser.windows.getLastFocused(R(d,2));if(d.wait())return}else if(c){var e=this.b[c.id],f=this.a[e&&e.s];f&&(a.a=f.id)}var h=this.h[a.a];if(!h)return S(this,a,0);var g=a.$;g||(g=Za.prototype.Sa++,a.$=g,this.I[g]=a);var l=g;(f=this.a[h.tabId])&&f.update&&(f.update=!1,f.postMessage([14,!0]));var k=a.b[8];b=[15,l,k];k||(h.A||Bb(this,h,l),b.push(a[6],a[17],a[50],a[31],a[133]));h.postMessage(b)}catch(m){S(this,a,0)}};
function S(a,b,c,d,e,f,h,g){-1!=c&&(e=[b.l,c,e,h,f],f={},f[8]=b[8],g&&(f[110]=g),M(a,1,2,d|(0==c?4:2),e,f))}n.Pb=function(a){mb(this,a).a=!0};
n.kb=function(a,b){var c=a.tabId,d=a.frameId,e=a.url,f=a.transitionType,h=f&&f.endsWith("_subframe");this.M!=c||Ka(e)||(this.M=null);if(f=this.a[c+","+d])if(this.l&&(a=this.b[f.a])&&a.s==this.l&&this.J(4294967295),b){if(e!=f.i){b=this.f;var g,l;for(l in b)if(g=b[l],g.port===f)2==f.j?Fb(this,l):(this.J(l),delete b[l]);f.m++;f.i=e;f.A&&(f.update=!0);f.postMessage([17,!0])}}else this.pa(f,!0),h&&"about:blank"==f.i&&this.oa(c,d);else h&&"about:blank"==e?(mb(this,a),this.oa(c,d)):(e=L(this,a))&&e.a&&(e.i||
!b)&&(e.a=!1)};n.Ib=function(a){return this.kb(a,!0)};n.nb=function(a,b){var c=a.id;a={I:c,width:a.width,height:a.height,left:a.left,top:a.top,a:this.xa,c:8,H:oa,g:0,u:0,l:"maximized"==a.state,f:"minimized"==a.state,C:"fullscreen"==a.state,D:0,G:0,s:0,m:!y,b:null,L:null};Object.setPrototypeOf(a,bb.prototype);this.b[c]=a;b&&(browser.tabs.query({windowId:c,active:!0},this.V),browser.tabs.query({windowId:c,url:G},this.nc),browser.tabs.query({windowId:c,url:G},this.oa));return a};
n.nc=function(a){for(var b;b=a.shift();)mb(this,0,!0,b.id,b.url)};n.ob=function(a){M(this,5,1,32,[a]);delete this.b[a]};n.ec=function(a){if(0<a){var b=this.b[a];b&&(b.b||Lb(this,b,!0),(b=this.a[b.s])&&b.b&&(b.b=!1,browser.tabs.reload(b.tabId)),v&&this.Ma(a,!1,!0,500))}};n.Zb=function(a,b,c){var d=c.windowId,e=this.b[d];e&&(e.b||Lb(this,e),e.s||this.V(c));"complete"==b.status&&(a=this.a[a])&&!a.loaded&&(a.loaded=!0,this.aa(d))};
n.Yb=function(a){var b=this.a,c=this.G,d=a+",";this.M==a&&(this.M=null);(a=b[a])&&this.pa(a,!0);for(var e in b)e.startsWith(d)&&this.pa(b[e],!0);for(var f in c)f.startsWith(d)&&delete c[f]};n.Wb=function(a){this.ua=0;this.l&&this.J(4294967295);var b=a.windowId;a=a.tabId;var c,d=this.a[a];d&&(d.a||(d.a=b),c=d.b)&&(d.b=!1);if(d=this.b[b]){var e=d.s;d.s=a;this.M==e&&(this.M=null,window.setTimeout(browser.tabs.remove.bind(null,e),250));Ib(this,e);browser.tabs.get(a,this.V);c||this.aa(b)}c&&browser.tabs.reload(a)};
n.Xb=function(a,b){b=b.newWindowId;var c=this.h,d;for(d in c)(d=c[d])&&d.tabId==a&&(d.a=b);Ib(this,a,!0)};n.ib=function(a,b,c){if(a.A){var d=a.tabId;a=a.a;var e=this.b[a];this.l&&this.J(4294967295);e&&e.s==d&&(b&&(e.G=b),c&&(e.D=c),Ib(this,d),this.Ma(a,b||c,!1,500))}else a.na&&(b=this.a[a.f])&&b.postMessage([16,null,a.Y,a.na])};n.Lb=function(a,b,c){(b=Wa[b])&&Jb(this,b,c,a)};n.Ob=function(a,b,c){0==b&&Jb(this,32,c,a)};n.Mb=function(a,b,c){a.linkUrl=b;a.u=c};n.Hb=function(){Jb(this,63,!1)};
n.Kb=function(a,b,c,d,e){b&&(b=a.c)&&(a=32,d=[b,null==d?(a|=16,-2):d],b={},b[110]=c,b[115]=e,M(this,16,1,a,d,b))};n.fc=function(a,b,c){if(a=this.g[b]){b=[b,0];var d={};d[115]=c;M(this,16,1,48,b,d);a.ma=!1;a.gb&&Y(this,a)}};n.Ub=function(a,b,c,d){M(this,19,2,0,[b,c,a.tabId,a.c],d)};function Ub(a,b){if(b=a.g[b]){var c=b.ea;b.ma=!1;b.ea=null;b.gb&&Y(a,b);c&&c.abort()}}n.Tb=function(a,b){if(4==a.readyState){var c=[b,0],d={};200==a.status&&(d[115]=a.response);M(this,16,1,48,c,d);Ub(this,b)}};
function Wb(a,b){var c=a.c;if(!c[-9]||b.qa)return 1;if(b.X)return 6;if(b.N&&c[-4])return 1;var d=b.Oa,e=b.urlType=Xb(d.pathname);return c[9].test(d.hostname)||c[19].test(d.href)?1:2==(b.K&7)&&(b.Ha||c[-13])?d.pathname.endsWith("/")||c[21].test(d.pathname)?1:c[1].test(e)||a.j&&!c[20].test(e)?4:1:6}
function Yb(a,b){if(b.O)return 6;if(b.X)return 3;var c=a.c,d=c[18],e=c[1],f=b.Oa,h=b.urlType,g=f.search?null:h,l=b.N,k=ta.includes(b.type),m=!b.Ha,p=!k&&d.exec(f.href);if(p){var q=d.rc,r=d.sc,E=d.tc,C=d.uc;for(d=1;d<p.length;++d)if(p[d]){q=q[--d];if(null===q)break;p=0;var x=q.includes("V")|q.includes("A")|q.includes("C");if(l&&!x&&!q.includes("S")||m&&q.includes("D"))return 1;if(q.includes("G")){var w=!0;p|="GET"==b.method}q.includes("P")&&(w=!0,p|="POST"==b.method);if(w&&!p)break;if(p=C[d]){p=p.exec(f.href);
if(!p)break;f=r[d];if(r=f.F){var B=!0;var U=p[r]}if(r=f.T){B=!0;var D=p[r]}}D||(D=Xb(U)||q.includes("T")&&(B=!0,h)||E[d]);if(x)D&&(g=b.urlType=D),l||(l=b.N=!0);else if(D?e.test(D):!B)return b.La=16777216,4;break}}if(g&&(k&&c[2].test(g)||l&&c[4].test(g)))return 1;if((y||a.H)&&(b.Ha||c[-13])){if(l&&c[3].test(g))return 6;if((!l||a.j)&&g&&e.test(g))return b.La=8,4}return 6}
function Zb(a,b){if(b.Cb)return a.P(6,b),6;var c=b.statusCode;if(200!=c&&206!=c)return 1;var d=Z(b.responseHeaders,"Content-Type"),e=Z(b.responseHeaders,"Content-Disposition"),f=$b(d).toLowerCase(),h="attachment"==$b(e).toLowerCase();c=b.N;var g=b.Z;if(b.Bb=g&&!h&&"text/html"==f){if(b.B){var l=L(a,b);l&&(l.B=!0);a.P(5,b)}return 1}if(c?b.qa:b.O)return 1;if(a.j&&g&&h)return 4;var k,m,p,q=a.c,r=b.Oa,E=r.hostname,C=r.pathname;e=(d=ac(e,"filename")||ac(d,"name"))&&Xb(d);if(d)if(e){b.fileName=d;var x=p=
!0}else if(!c)return 1;p||(d=C.split("/").pop(),(e=b.urlType||Xb(d))&&e.toLowerCase()==f.split("/").pop()&&(x=!0));if(!x){var w=q[10].test(f),B=Ya[f];if(B)if(B=B.split("|"),e&&B.includes(e))x=!0;else if(c?!w:!e){x=!0;var U=w;e=B[0]}!x&&e&&(h&&g?x=!0:w?x=U=!0:B||Na(e)||(x=U=!0))}if(c){B=sb(a,E);g=a.W[B];w=C+r.search;switch(B){case 1:if(g[111].test(w))var D=x=!0;else if(g[112].test(w))var V=!0;else if(g[115].test(w)&&"application/json"==f)var ob=!0;else if(g[113].test(w)&&"application/x-www-form-urlencoded"==
f||g[114].test(w)&&"video/vnd.mpeg.dash.mpd"==f)var la=!0;break;case 2:(E=g[111].exec(w))&&Ma(f)?(f=E[1]&&g[112].exec(b.port.i))&&E[1]!=f[1]||(la=!0):g[114].test(w)?ob=!0:h&&"image"==b.type&&"MP4"==e&&(m=!0);break;case 3:"M4S"==e&&(x=!0),E==g[111]&&g[112].test(C)&&"application/json"==f&&(la=!0)}x&&("M3U8"==e||"F4M"==e||a.Ta&&"MPD"==e?la=!0:"F4F"==e&&(d.endsWith("Seg1-Frag1")||d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(k=!0));"ASF"==e&&((f=Z(b.responseHeaders,"Content-Length"))&&102400>=
parseInt(f)&&(m=!0),"DCLK-AdSvr"==Z(b.responseHeaders,"Server")&&(m=!0))}if(m)return 1;x&&(c&&q[3].test(e)?D=!0:c&&q[4].test(e)?b.O=!0:!b.O&&q[1].test(e)&&(l=!0));if(D){var pb,qb;if(m=q[11])m.test(r.hostname)?D=!1:(pb=a.a[b.tabId])&&(qb=pb.i)&&m.test((new URL(qb)).hostname)&&(D=!1)}la||k?"POST"!=b.method||b.U?(a=new XMLHttpRequest,a.responseType=k?"blob":"text",b.ea=a,V=!0):V=!1:ob&&(V=b.ma=!0);if(!l&&!D&&!V)return 1;x&&(b.Ea=e);p&&(b.fileName=d);b.B|=V;b.La=D||V?256:16|(c?4096:0)|(U?8388608:0);return l?
4:D?2:5}
n.P=function bc(a,b,c,d,e,f){var g=b.url,l=b.K||zb(g),k=1==(l&7),m=b.requestHeaders;if(k&&!d&&!e&&(f=Z(m,"Cookie"),null==f))return O(g,bc.bind(this,a,b,c,d,!0)),!0;K(f)&&(f=P(f));var p=b.id,q=b.port&&b.port.id,r=b.timeStamp,E=c?Math.floor(c.timeStamp-r):null,C=b.La,x=b.responseHeaders;e=b.pb;var w=c&&c.ip;c=0;3==cc(w,".")?C|=33554432:2<cc(w,":")&&(C|=4194304);l&16&&(C|=2097152);"POST"==b.method&&(C|=512);4>a&&(y||d)&&(c|=1);b.B&&b.ea&&(c|=1);b.B&&5!=a&&(c|=32);b.N&&(c|=16);b.Z&&(c|=b.A?2048:4096);
l=[p,q,Math.floor(r/1E3),Math.floor(r%1E3*1E3),l&7,a,b.tabId,b.frameId];p={};p[6]=N(g,k&&4>a);p[17]=b.S;p[4]=b.Ea;p[100]=b.fileName;p[8]=C;p[129]=E;p[122]=this.m;p[11]=dc(m);p[13]=dc(x);p[18]=dc(e);b.U&&(p[14]=Tb(b.U,Z(m,"Content-Type")));b.Ja&&(p[19]=Tb(b.Ja,Z(e,"Content-Type")));if(null==m){a=this.G;g=b.tabId+","+b.frameId;do g=(k=a[g])&&k.b,k=k&&k.i,"about:blank"==k&&(k=null);while(!k&&g);p[50]=k;p[51]=f;p[54]=navigator.userAgent}y&&(p[122]=hb(this,b.proxyInfo,Z(m,"Proxy-Authorization")),p[55]=
hb(this,b.qb,Z(e,"Proxy-Authorization")));if(!b.Bb||!b.A)if(b=this.a[b.tabId])p[7]=b.i;return M(this,13,1,c,l,p,d)};n.ba=function ec(a,b,c,d,e){if(void 0===a)b.resolve=d,b.reject=e,lb(this,b);else{d=this.H?new XMLHttpRequest:null;e=this.P(a,b,c,d);d&&(e=(d=e&&parseInt(d.getResponseHeader("x-idm-status")))?3==d:this.P(a,b,c));if(e)return Ga&&!c?void(b.Ga=!0):y?new Promise(ec.bind(this,void 0,b,null)):Y(this,b,!0);b.O=!0}};
function Y(a,b,c){var d=a.g,e;if(K(b))var f=b.id;else if(!(b=d[f=b]))return;if(c){if(b.Z||b.fb){var h=0<b.statusCode||!b.requestHeaders,g=L(a,b);g&&g.a&&b.A?browser.tabs.remove(b.tabId):u&&h&&!b.fb?e={redirectUrl:"javascript:void(0)"}:v&&h?e={redirectUrl:fc(b,g)}:Ia&&h&&(e={redirectUrl:a.D||fc(b,g)})}e||(e={cancel:!0});b.Ga=!0}(a=b.resolve)&&void 0!==c&&(b.resolve=b.reject=null,a(e||{}));if(c=b.reject)b.resolve=b.reject=null,c();if(b.ea||b.ma)return b.gb=!0,e;delete d[f];v&&delete d[b.requestId];
return e}n.Db=function(a){var b=this.c;(this.j||a.byExtensionId)&&b[-9]&&!this.ya&&zb(a.finalUrl||a.url,!0)&&(this.ga[a.id]=a,browser.downloads.pause(a.id,W))};
n.Eb=function(a,b){var c=a.id,d=this.ga;if(!d[c])return!1;var e=this.c,f=a.finalUrl||(a.finalUrl=a.url),h=new URL(f),g=a.K=zb(f,!0),l=a.Ea=Xb(a.filename||h.pathname);if(!(a.X=this.ta)&&!this.j&&(!e[1].test(l)||e[9].test(h.hostname)||e[19].test(h.href)))return Sb(this,c);a.lc=b;d[c]=a;if(1==g){if(!a.referrer){b=this.h;c=this.b;for(var k in b)if(d=b[k],d.i==f&&(a.referrer=d.Ka,(e=c[d.a])&&e.s==d.tabId))break}k=new Q(this.hb,a);O(f,R(k,1));a.url!=f&&O(a.url,R(k,2));if(k.wait())return a.eb=!0}return this.hb(a)};
n.hb=function(a,b,c){var d=Date.now();d=[a.id,0,Math.floor(d/1E3),Math.floor(d%1E3*1E3),a.K,2];var e={};e[6]=N(a.finalUrl);e[4]=a.Ea;e[103]=a.totalBytes||null;e[100]=a.filename||null;e[127]=a.mime||null;e[8]=a.X?2048:0;e[50]=a.referrer||null;e[51]=P(b);e[54]=navigator.userAgent;e[122]=this.m;a.finalUrl!=a.url&&(e[17]=N(a.url),e[56]=P(c));return M(this,13,1,129,d,e)||Sb(this,a.id)};
function Sb(a,b,c){var d=a.ga[b];if(d){if(c)return browser.downloads.cancel(b,W),!0;d.eb&&(d.eb=!1,d.lc());browser.downloads.resume(b,W);delete a.ga[b]}return!1}n.$b=function(a){var b=new URL(a.url);if(b.search.startsWith("?d=")){var c=this.a[a.tabId];this.fa("idmreg:"+b.href.substr(b.protocol.length),null,c&&c.i);Y(this,a.requestId);(b=L(this,a))&&b.a&&"main_frame"==a.type&&browser.tabs.remove(a.tabId);return{redirectUrl:Ca+"?register=1"}}};
n.mb=function(a){var b=a.type,c=a.tabId,d=a.frameId;if(!(ma&&!va.includes(b)||0>c&&0==d)){var e=a.url,f=a.method,h=zb(e);if(h&&("GET"==f||"POST"==f)&&e!=this.D){var g=a.id=v?String(this.zb++):a.requestId,l=this.g[g],k=this.ya,m="POST"==f;f="image"==b;var p=u&&0>c&&"other"==b,q=!p&&0>c&&0>d,r=0<c&&b.endsWith("_frame");c=q?null:this.a[c+","+d];y&&m&&l&&Ra(l.statusCode)&&(a.method="GET",m=!1);r&&(d=mb(this,a,!1),d.c!=g&&(d.c=g,d.h=e,d.B=!1),d.g=m);if(c||r||q||p||l){if(!k&&m&&a.requestBody){g=a.requestBody;
if(m=g.raw)for(d=0;d<m.length&&(m[d].bytes||(m=null));d++);if(!(m||g.formData||u&&g.error))return}g=new URL(e);g.hash="";a.Oa=g;a.K=h;a.X=this.ta;a.qa=k;a.A=r&&"main_frame"==b;a.Z=r;a.fb=p;a.vb=q;a.N=q||ua.includes(b);a.O=f;a.B=this.Ua.test(e);a.U=a.requestBody;a.port=c;a.Ha=h&8||(y?a.proxyInfo&&"https"==a.proxyInfo.type:this.la[h]);l&&(a.id=l.id,a.port=c=l.port,a.X=l.X,a.qa=l.qa,a.S=l.S||l.url,a.pb=l.pb||l.requestHeaders,a.Ja=l.Ja||l.U,y&&(a.qb=l.qb||l.proxyInfo));if(a.N&&!f){b=this.ha;for(h=b.jc;30<=
h.length;)delete b[h.shift()];b[e]=c;h.push(e)}switch(a.action=Wb(this,a)){case 1:a.O=!0;case 6:lb(this,a);break;case 4:return this.ba(1,a)}}}}};
n.ac=function(a){var b=this.g[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.Ga){if(b.vb&&!b.port&&(a=Z(c,"Referer")))for(var d of T(this.h))if(d.i==a){b.port=d;break}y&&b.proxyInfo&&hb(this,b.proxyInfo,Z(c,"Proxy-Authorization"),!0);if("POST"==b.method&&(!b.U||b.U.error&&0<Z(c,"Content-Length")))return Y(this,b);switch(b.action=Yb(this,b)){case 1:b.O=!0;break;case 4:return this.ba(1,b);case 3:return this.ba(3,b)}}}else if(0>a.tabId&&"xmlhttprequest"==a.type&&
(a.initiator?a.initiator==Da:a.originUrl?a.originUrl==Ea:1)){b=a.requestHeaders;c={};d=!1;for(a=0;a<b.length;a++){var e=b[a],f=e.name.toLowerCase();f.startsWith("x-idm-")?c[f.substr(6)]=d=!0:"origin"==f&&e.value==Da&&(c[f]=d=!0)}if(d){for(a=0;a<b.length;a++)e=b[a],f=e.name.toLowerCase(),c[f]?b.splice(a--,1):f.startsWith("x-idm-")&&(e.name=e.name.substr(6));return{requestHeaders:b}}}};
n.cc=function(a){var b=this.g[a.requestId];if(b){var c=b.statusLine=a.statusLine,d=b.statusCode=a.statusCode||parseInt(c.split(" ",2).pop());if(b.Ga||204==d&&c.includes(" IDM "))return Y(this,b,!0);c=b.responseHeaders=a.responseHeaders;b.Cb=Qa(d);if("image"==b.type&&(d=Z(c,"Content-Type"))&&d.toLowerCase().startsWith("image"))return Y(this,b);"quic"==Z(c,"Client-Protocol")?b.K|=16:(d=Z(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Z(c,"Transfer-Encoding")&&(b.K|=16);switch(b.action=
Zb(this,b)){case 1:return Y(this,b);case 4:return this.ba(2,b,a);case 3:return this.ba(3,b,a)}if(b.ma)return c.push({name:"X-IDM-Request-ID",value:b.id.toString()}),{responseHeaders:c}}};n.dc=function(a){if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){var b=L(this,a);b&&(b.i=a.url,b.S=b.h)}if(b=this.g[a.requestId])2==b.action?this.P(4,b,a):5==b.action&&this.P(5,b,a),Y(this,b)};n.bc=function(a){Y(this,a.requestId)};
n.Ba=function(a,b,c,d,e){var f=fa&&"llbjbkhnmlidjebalopleeepgdfgcpec"==browser.runtime.id&&"ngpampappnmepgilojfohadhhmbhlaek";if(!a&&(this.za=!1,a=new Q(this,!0),browser.storage.local.get("version",R(a,1)),(y?1124073472<=z:v?1073741824<=z:1)&&browser.extension.isAllowedIncognitoAccess(R(a,2)),u&&browser.management.get("jeaohhlajejodfjadcponpnjgkiikocn",R(a,3)),fa&&browser.management.get(f||"llbjbkhnmlidjebalopleeepgdfgcpec",R(a,4)),a.wait()))return;K(d)&&d.enabled&&browser.management.setEnabled(d.id,
!1);K(e)&&e.enabled&&browser.management.setEnabled(f||browser.runtime.id,!1);K(b)&&(b=b.version||"");if((f=Ba.version||"")&&f!=b&&null!=b&&(browser.storage.local.set({version:f}),d=this.Ya,e=this.Pa,!b||!d||e)){f="current="+escape(f);b&&(f+="&previous="+escape(b));d&&(f+="&manager="+(d?[d>>24&255,d>>16&255,d>>8&255,d&255].join("."):""));e&&(f+="&update=1");null!=c&&!c&&(f+="&incognito=1");y&&(f+="&mzffox=1");ha&&(f+="&opera=1");if(v||fa)f+="&msedge=1";browser.tabs.create({url:browser.runtime.getURL("welcome.html?"+
f)},function(h){h&&(this.M=h.id)}.bind(this))}};function Pb(a,b,c){null==b&&(b=(b=Aa.exec(c[13]))?b[1]<<24|b[2]<<16|b[3]<<8:0);a.Ya=b||0;a.Pa=102825984>b}function Db(a,b){b=browser.i18n.getMessage(b);y?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(b)+'")); true;'},W):window.alert(b)}n.v=function(a,b,c){if(null!=b){var d=da(arguments);if(y||v)d[2]=function(){return c.apply(null,arguments)};this.Ra.push(d);b.addListener.apply(b,d.slice(2))}};
function Q(a,b){this.caller=a instanceof Function?a:arguments.callee.caller;this.c=a instanceof Function?null:a;this.a=da(arguments,1);this.count=0;this.f=this.b=!1}function R(a,b){a.count++;return a.g.bind(a,b)}Q.prototype.wait=function(){return this.count?this.b=!0:this.f?(this.caller.apply(this.c,this.a),!0):!1};Q.prototype.g=function(a,b){browser.runtime.lastError;this.a[a]=b;0==--this.count&&(this.b?this.caller.apply(this.c,this.a):this.f=!0)};
function kb(a){return browser.i18n.getMessage(a)||a}function N(a,b){var c=a.lastIndexOf("#");c>a.indexOf("?")&&"!"!=a[c+1]&&(a=a.substr(0,c));b&&!Oa(a)&&(a="idmfc"+a);return a}function fc(a,b){var c=a.port;b=b&&!b.g;v&&(c&&a.url==c.linkUrl||(b=!1));return Ca+(b?"?back=1":"?host="+(new URL(c&&c.i||a.url)).hostname)}function O(a,b){v&&a.startsWith("ftp:")?b([]):(a={url:a},ka&&(a.firstPartyDomain=null),browser.cookies.getAll(a,b))}
function P(a){var b="";if(a&&a.length)for(var c=0;c<a.length;c++)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}function dc(a){if(!a||!a.length)return null;for(var b="",c=0;c<a.length;c++)b+=a[c].name,b+=": ",b+=a[c].value,b+="\n";return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(var c=0;c<a.length;c++)if(a[c].name.toLowerCase()==b)return a[c].value;return null}
function ac(a,b){if(!a)return null;a=a.split(";");for(b=b.toLowerCase();a.length;){var c=a.shift(),d=c.indexOf("=");if(0<d){var e=c.substr(0,d).trim().toLowerCase(),f="*"==e[e.length-1];if(f)e=e.substr(0,e.length-1).trimRight();else if(g)continue;if(e==b){c=c.substr(d+1).trim();d=c.length-1;if('"'==c[0]?'"'==c[d]:"'"==c[0]&&"'"==c[d])c=c.substring(1,d);if(f){if(c=c.split("'",3),f=c.shift().toLowerCase(),(d="utf-8"==f||"utf8"==f)||!g){var h=unescape(c.pop());var g=f;if(d)break}}else h=unescape(c)}}else 0>
d&&null==h&&c.trim().toLowerCase()==b&&(h="")}return h}function $b(a){const b=/[;,]/;return a&&(a=a.split(b,1).shift().trim())&&!a.includes("=")&&unescape(a)||""}
function Tb(a,b){var c=a.raw;if(c){var d=String.fromCharCode;a="";for(b=0;b<c.length;b++){var e=c[b].bytes;if(!e)return null;e=new Uint8Array(e);for(var f=e.length,h=0;h<f;h++)a+=d(e[h])}return a}c=a.formData;if(!c)return null;e=$b(b).toLowerCase();a=[];if(e&&"application/x-www-form-urlencoded"!=e)if("multipart/form-data"==e){(e=ac(b,"boundary"))||(e="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(f=c[d],b=0;b<f.length;b++)a.push("--",e,'\r\nContent-Disposition: form-data; name="',
d,'"\r\n\r\n',f[b]||"","\r\n");a.push("--",e,"--\r\n")}else return null;else for(d in c)for(f=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),b=0;b<f.length;b++)a.length&&a.push("&"),a.push(d,"=",(f[b]||"").split(" ").map(encodeURIComponent).join("+"));return a.join("")}function Xb(a){return(a=za.exec(a))?a.pop().toUpperCase():""}function zb(a,b){a=a.split(":",1).shift().toLowerCase();a=Xa[a]||0;return b?a&7:a}
function gc(a,b){browser.runtime.lastError;if(void 0===a){b=navigator.userAgent;a=b.match(/\b(?!(?:Safari|Chrome|Gecko)\/)\w+\/(\d+)(?:.(\d+))?(?:.(\d+))?(?:.(\d+))?\b(?!.*[()])/);if(b=y?a:b.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/)){z=b[1]<<24|b[2]<<22|b[3]<<8|b[4];ja=b[0];A=a?a[0]:b[0];u&&navigator.brave&&(A=A.replace("Chrome/","Brave/"));browser.runtime.getBrowserInfo&&browser.runtime.getBrowserInfo(gc);try{y&&browser.privacy.websites.firstPartyIsolate.get({},gc)}catch(c){}if(a=browser.webRequest.ResourceType)if(a.MEDIA&&
(va.push("media"),ua.push("media")),a.OBJECT_SUBREQUEST||(ma=y&&922746880>z))va.push("object_subrequest"),ua.push("object_subrequest")}u&&browser.management.get("clhiejnehegdfknplplojohghjaklbae",gc.bind(this,{}))}else"version"in a?(b=a.version.split(/\D+/),z=b[0]<<24|b[1]<<22|b[2]<<8|b[3],ja=A=a.name+"/"+a.version,Ia=939524096>z):"value"in a?ka=a.value:b&&(na=!0,A=A&&A.replace("Chrome/","Epic/"))}
function X(a,b,c,d){if(b=b[c]||void 0)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\."),b=1==d?b.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):b.replace(/\?/g,".").replace(/\*/g,".*?"),2==d&&(b=b.replace(/~/g,"(?:\\b[^.]+\\.)?")),b=RegExp("^(?:"+b+")$",1==d?"":"i")}catch(e){b=null}a[c]=b||ra}
function Qb(a,b,c,d,e){b=b[c];var f=[],h=[],g=[],l=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(d){for(var k=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");k.length;){var m=k.shift();f.push(Pa(m)?m:null);h.push(k.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(e){k=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");m=/<([A-Z]):(.*?)>/g;for(var p={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"},q,r=0;k.length;++r)if(q=k.shift()){for(var E={},C=["^"],x="",w,B=1;w=m.exec(q);++B)E[w[1]]=B++,x=RegExp.rightContext,C.push(RegExp.leftContext,"(",w[2].replace(/\*/g,p[w[1]]||".%%?"),")");C.push(x,"$");g[r]=E;l[r]=RegExp(C.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(m,"(?:$2)")}b=b.replace(/\*/g,".%%?").replace(/%%/g,"*");b=d||e?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(U){b=
null}a[c]=b||(b=/(?!)/);d&&(b.rc=f,b.tc=h);e&&(b.sc=g,b.uc=l)}function cc(a,b){var c=0;if(a)for(var d=0;0<=(d=a.indexOf(b,d));d++,c++);return c}function xb(a){return K(a)?a.source.replace("\\/","/"):a}function Ob(a,b){b&&browser.runtime.lastError||browser.permissions.request({permissions:[a]},b)}function W(a){browser.runtime.lastError;a;!0}const wb=Function.bind.bind(function(a){return this[a]}),Rb=Function.bind.bind(function(a){return a&&a[this]});var K=Object.isExtensible;
try{K(null)}catch(a){K=function(b){return b instanceof Object}}var T=Object.values;T||(T=function(a){return Object.keys(a).map(wb(a))});const jb=[[!0,-11,"menu_download_link","link,image",I.prototype.Da],[!0,-11,"menu_download_link","page,frame,editable",I.prototype.Da,ya],[!0,-11,"menu_download_selected","selection",I.prototype.ab],[!0,-12,"menu_download_all","page,frame,editable",I.prototype.ab],[u,-11,"menu_download_item","link",I.prototype.Da,["chrome://downloads/*"]]];gc();new I;

