var g;
if(!window.__idm_init__){window.__idm_init__=!0;Array.prototype.includes||(Array.prototype.includes=function(b,a){return 0<=this.indexOf(b,a)});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);"undefined"==typeof browser&&(browser=chrome);navigator.userAgent.includes("Edge/");navigator.userAgent.includes("Firefox/");navigator.userAgent.includes("OPR/");
var r=Array.prototype.includes,v=Function.call.bind(Array.prototype.slice),w=Function.apply.bind(Array.prototype.push),x=Function.call.bind(Array.prototype.forEach),y={16:!0,17:!0,18:!0,45:!0,46:!0},B=["video","audio","object","embed"],C=r.bind(B),I=/(?!)/,J=window.self===window.top,K=window.origin||document.origin||location.origin;function D(){J&&(this.na=0);this.sa=[];this.G=[];this.j={};this.ga();window.__idm_connect__=this.ga.bind(this,!0);this.b(1,window,"resize",this.Xa);this.b(1,window,"scroll",
this.Ya);this.b(1,window,"blur",this.Qa);this.b(1,window,"keydown",this.pa,!0);this.b(1,window,"keyup",this.pa,!0);this.b(1,window,"mousedown",this.Sa,!0);this.b(1,window,"mouseup",this.Ua,!0);this.b(1,window,"mousemove",this.Ta,!0);this.b(1,window,"click",this.Ra,!0);this.b(1,document,"beforeload",this.Oa,!0);this.b(1,document,"DOMContentLoaded",this.oa);"interactive"!=document.readyState&&"complete"!=document.readyState||this.oa()}g=D.prototype;g.c=0;g.f=0;g.P=-1;g.R=-1;g.va=1;g.g="";g.Z="";g.aa=
I;g.ea=I;g.fa="";g.A=I;g.h={};g.ba=I;g.ca=I;g.da=I;g.Y=I;g.T=":root:empty";g.V=":root:empty";g.U=":root:empty";g.u=":root:empty";g.W=":root:empty";g.S=":root:empty";g.X=":root:empty";g.v=0;g.$=I;g.ga=function(b){this.qa(-1);this.a=b=browser.runtime.connect({name:(J?"top":"sub")+(b?":retry":"")+("file:"==location.protocol?":file":"")});this.I=b.id||b.portId_||this.I||Math.ceil(1048575*Math.random());this.b(-1,b,"onMessage",this.Wa);this.b(-1,b,"onDisconnect",this.Va)};g.Va=function(){browser.runtime.lastError;
this.qa();this.a=this.I=null;window.__idm_init__=!1;window.__idm_connect__=null};g.Wa=function(b){switch(b.shift()){case 11:this.Da.apply(this,b);break;case 17:this.Ea.apply(this,b);break;case 12:this.Fa.apply(this,b);break;case 13:this.xa=b.shift();break;case 14:this.Ia.apply(this,b);break;case 15:this.Ja.apply(this,b);break;case 16:this.Ka.apply(this,b);break;case 18:this.Ha.apply(this,b)}};g.$a=function(b,a){switch(this.J=b){case 1:this.ya=this.O=!0;this.g=a.shift()||"";this.aa=RegExp(a.shift()||
"(?!)");this.A=RegExp(a.shift()||"(?!)");this.fa=a.shift()||"";this.h=(a.shift()||"").split(/[|:]/).reduce(L,{});this.ba=RegExp(a.shift()||"(?!)");this.ca=RegExp(a.shift()||"(?!)");this.da=RegExp(a.shift()||"(?!)");this.ea=RegExp(a.shift()||"(?!)");break;case 2:this.O=!0;this.g=a.shift()||"";this.Z=a.shift()||"";this.Y=RegExp(a.shift()||"(?!)");this.T=a.shift()||":root:empty";this.V=a.shift()||":root:empty";this.U=a.shift()||":root:empty";this.u=a.shift()||":root:empty";this.W=a.shift()||":root:empty";
this.S=a.shift()||":root:empty";this.X=a.shift()||":root:empty";this.v=a.shift()||0;break;case 3:this.$=RegExp(a.shift()||"(?!)")}this.g.startsWith("^/")&&(this.g="^(?:"+K.replace(/\./g,"\\.")+")?"+this.g.substr(1))};g.K=function(b){if(this.J&&this.s(arguments))switch(this.J){case 1:this.Na(b);break;case 2:this.La(b);break;case 3:this.Ma(b)}};g.B=function(){if(!this.ua){this.ua=!0;this.b(2,window,"message",this.Za);var b=document.createElement("script");b.src=browser.extension.getURL("document.js");
b.onload=b.remove.bind(b);document.documentElement.appendChild(b)}};g.Za=function(b){var a=b.data;if(Array.isArray(a)&&b.origin==K)switch(a[0]){case 1229212977:window.postMessage([1229212978,this.O,this.ya,this.g,this.Z],"/");break;case 1229212979:this.a.postMessage([36,parseInt(a[1]),a[2]])}};g.H=function(){var b=window.devicePixelRatio,a=document.width,c=document.body.scrollWidth;a&&c&&(b=a==c?0:a/c);return b};g.o=function(b){try{var a=parseInt(b.getAttribute("__idm_id__"));a||(a=this.I<<10|this.va++,
b.setAttribute("__idm_id__",a),this.j[a]=b);return a}catch(c){return null}};g.Ca=function(b,a,c,d,e){try{var f=document.activeElement,m=f&&C(f.localName)?f:null;m||(m=(f=document.elementFromPoint(this.P,this.R))&&C(f.localName)?f:null);var l=0,n,h=0;a:for(;h<B.length;h++)for(f of document.getElementsByTagName(B[h]))if(!(2<=h&&"text/html"==f.type.toLowerCase()||3==h&&"application/x-shockwave-flash"!=f.type.toLowerCase())){if(e&&f.getAttribute("__idm_link__")==e){var k=f;break a}var p=f.src||f.data;
if(p)p!=b&&p!=a||(k=f);else if(2>h)for(var z of f.getElementsByTagName("source"))if((p=z.src)&&(p==b||p==a)&&(k=f))break;if(k){var q=window.getComputedStyle(f);if("cover"==q.objectFit){var M=f;k=null;continue}break a}if(!m&&!E)if(!p||p!=c&&p!=d){var t=f.clientWidth,u=f.clientHeight;if(t&&u){var F=f.getBoundingClientRect();if(!(0>=F.right+window.scrollX||0>=F.bottom+window.scrollY)&&(q=window.getComputedStyle(f),"hidden"!=q.visibility&&"cover"!=q.objectFit)){var G=t*u;if(G>l&&1.35*t>u&&t<3*u){l=G;
var N=f}n||(n=f)}}}else var E=f}b=k||M||m||E||N||n;if(!b)return null;if("embed"==b.localName&&!b.clientWidth&&!b.clientHeight){var H=b.parentElement;"object"==H.localName&&(b=H)}return this.o(b)}catch(O){}};g.Ba=function(b,a,c){var d=null,e;for(e of document.getElementsByTagName("iframe")){try{var f=parseInt(e.getAttribute("__idm_frm__"))}catch(l){}if(f==b){d=e;break}if(!d){var m=e.src;!m||m!=a&&m!=c||(d=e)}}return d&&this.o(d)};g.m=function(b){var a=null;try{var c=b.getBoundingClientRect(),d=Math.round(c.width),
e=Math.round(c.height);switch(b.localName){case "video":(b.videoWidth||b.hasAttribute("__idm_link__"))&&document.contains(b)&&(a=!1);if(15>d||10>e)return a;break;case "audio":if(!d&&!e)return a;var f=!0}var m=document.documentElement,l=m.scrollWidth||m.clientWidth,n=m.scrollHeight||m.clientHeight,h=Math.round(c.left)+b.clientLeft,k=Math.round(c.top)+b.clientTop;if(h>=l||k>=n||f&&!h&&!k)return a;0==h&&k==-n&&d==l&&e==n&&(k=0);a=[h,k,h+d,k+e,this.H()]}catch(p){}return a};g.i=function(){try{var b=window.top.document.title}catch(a){}b||
(b=(b=document.head.querySelector('meta[property="og:title"]'))&&b.getAttribute("content"));b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," ").trim());return b};g.Ga=function(){if(!document.elementsFromPoint)return 0;var b=document.documentElement,a=b.clientWidth||b.offsetWidth;b=(b.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0),d=0,e=0,f=0,m;for(m of c)if(m.offsetWidth>=a){var l=window.getComputedStyle(m);.95<=l.opacity&&(c=l.zIndex,"fixed"==l.position?(l=
m.offsetHeight+m.offsetTop,d<l&&l<b&&(d=l,e=c)):f<c&&(f=c))}e<f&&(d=0);return d};g.Da=function(b,a,c,d,e){if(a){this.na=a;try{window.frameElement&&window.frameElement.setAttribute("__idm_frm__",a)}catch(f){}}this.ja(c);e&&this.$a(e,v(arguments,5));"loading"==document.readyState?this.ta=!0:this.K()};g.Ea=function(b){this.M&&this.c&&(this.c=0,this.N=window.setTimeout(this.L.bind(this,!1),3E3));this.K(!0);b&&this.ja()};g.ja=function(b){if(this.s(arguments)){var a=[21,this.bb||location.href,document.referrer];
b&&a.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.a.postMessage(a)}};g.Ia=function(b){var a=b?this.s(arguments):1;if(0<a||0>a&&1!=this.J){a=this.i();var c=this.H(),d=this.Ga();this.a.postMessage([24,a,c,d])}};g.Ka=function(b,a,c,d,e){c||(c=this.Ba(a,d,e));d=(d=c&&this.j[c])&&this.m(d);this.a.postMessage([22,b,a,c,d])};g.Ha=function(b,a){var c=document.getElementsByTagName("a"),d;for(d of c)try{if(d.href==a){var e=d.download||null;var f=d.innerText.trim()||
d.title||null;break}}catch(m){}this.a.postMessage([35,b,e,f])};g.Ja=function(b,a,c,d,e,f,m){if(this.s(arguments)){var l=!a;l&&(a=this.Ca(c,d,e,f,m));var n=[23,b,a,!1];if(a){var h=this.j[a];if(h){var k=this.m(h);null!=k?(n[4]=k,l&&(n[5]=h.localName,n[6]=h.src||h.data,n[7]=h.getAttribute("operadetachedviewtitle"),this.ka.observe(h,{attributes:!0,attributeFilter:["style"]}))):document.contains(h)||(delete this.j[a],n[3]=!0)}else n[3]=!0}l&&!n[7]&&(n[7]=this.i());this.a.postMessage(n)}};g.Fa=function(b,
a,c,d){var e=d?RegExp(d,"i"):null;d=this.ia(document,e,a);var f=document.getElementsByTagName("iframe"),m;for(m of f)try{var l=m.contentDocument;l&&!m.src&&w(d,this.ia(l,e,a))}catch(n){}b=[27,b,this.na,d.length];c||(b[4]=d,b[5]=location.href,J&&(b[6]=location.href,b[7]=document.title));this.a.postMessage(b)};g.ia=function(b,a,c){var d=[],e={},f="",m="",l=!c;if(c){var n=b.getSelection();if(!n||n.isCollapsed&&!n.toString().trim())return d}for(var h of b.getElementsByTagName("a"))if(l||n.containsNode(h,
!0))try{var k=h.href;k&&!e[k]&&a.test(k)&&(e[k]=d.push([k,2,h.download||null,h.innerText.trim()||h.title]));c&&e[k]&&(f+=h.innerText,f+="\n")}catch(q){}for(h of b.getElementsByTagName("area"))if(l||n.containsNode(h,!0))try{(k=h.href)&&!e[k]&&a.test(k)&&(e[k]=d.push([k,2,null,h.alt]))}catch(q){}if(l)for(h of b.getElementsByTagName("iframe"))try{(k=h.src)&&!e[k]&&a.test(k)&&(e[k]=d.push([k,4]))}catch(q){}var p=c&&n.toString();if(p){f=this.l(f);for(k of this.l(p))k&&!e[k]&&a.test(k)&&!f.includes(k)&&
(e[k]=d.push([k,1]))}if(c)for(h of b.getElementsByTagName("textarea"))if(c=h.selectionStart,p=h.selectionEnd,(f=n.isCollapsed&&c<p)||n.containsNode(h,!0))try{var z=f?h.value.substring(c,p):h.value;for(k of this.l(z))k&&!e[k]&&a.test(k)&&(e[k]=d.push([k,1]))}catch(q){}if(l||!d.length)for(h of b.getElementsByTagName("img"))if(l||n.containsNode(h,!0))try{(k=h.src)&&!e[k]&&a.test(k)&&(e[k]=d.push([k,3,null,"<<<=IDMTRANSMITIMGPREFIX=>>>"+h.alt])),l&&h.onclick&&(m+=h.onclick,m+="\n")}catch(q){}if(l){for(h of b.getElementsByTagName("script"))m+=
h.innerText,m+="\n";if(m)for(k of this.l(m))k&&!e[k]&&a.test(k)&&(e[k]=d.push([k,5]))}return d};g.l=function(b){if(!this.ra){var a="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(d){return this[d]}.bind({"%H":"\\w\\-\u00a0-\ufeff","%T":"\\w\\-.+*()$!,%\u00a0-\ufeff","%Q":"^\\s\\[\\]{}()"}));this.ra=RegExp(a,"gi")}for(var c=[];a=this.ra.exec(b);)c.push(a.shift());return c};g.s=function(b){var a=this.c;a||(b=
v(b&&b.callee?b:arguments),b.unshift(arguments.callee.caller),this.G.push(b));return a};g.oa=function(b){try{var a=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.c=b&&a?-1:1;a&&(b=this.M,b||(this.M=b=new MutationObserver(this.L.bind(this))),b.observe(a,{childList:!0}));this.ka=new MutationObserver(this.Pa.bind(this));this.ta&&(this.ta=!1,this.K());for(b=this.G;a=b.shift();)a.shift().apply(this,a)};g.Pa=function(b){var a=b.length&&b[0].target;a&&(b=parseInt(a.getAttribute("__idm_id__")),
a=this.m(a),b&&a&&this.a.postMessage([23,null,b,!1,a]))};g.L=function(b){if(b)window.clearTimeout(this.N),this.N=window.setTimeout(this.L.bind(this,!1),1E3);else{0>this.c?this.c=1:++this.c;for(var a=this.G;b=a.shift();)b.shift().apply(this,b)}};g.Oa=function(b){var a=b.target,c=a.localName;C(c)&&b.url&&(a=this.o(a),this.a.postMessage([25,a,c,b.url]))};g.pa=function(b){!b.repeat&&y[b.keyCode]&&this.a.postMessage([31,b.keyCode,"keydown"==b.type])};g.Sa=function(b){this.xa&&this.a.postMessage([28]);
if(0==b.button){var a=b.view.getSelection();a&&a.isCollapsed&&!a.toString().trim()&&(this.f=1);this.a.postMessage([32,b.button,!0])}};g.Ua=function(b){if(0==b.button){this.P=b.clientX;this.R=b.clientY;this.a.postMessage([32,b.button,!1]);var a=b.view.getSelection();a&&this.f&&(this.f=a.isCollapsed&&!a.toString().trim()?0:2)&&this.a.postMessage([26,b.clientX,b.clientY,this.H()])}};g.Ta=function(){2==this.f&&(this.f=0)};g.Ra=function(b){b=b.target;"a"==b.localName&&this.a.postMessage([39,b.href,b.download])};
g.Ya=function(){this.a.postMessage([29])};g.Xa=function(b){b=b.target;this.a.postMessage([30,b.innerWidth,b.innerHeight])};g.Qa=function(){this.f=0;this.a.postMessage([33])};g.b=function(b,a,c,d,e){var f=v(arguments);f[3]=d.bind(this);this.sa.push(f);0>b?(a=a[c],a.addListener.apply(a,f.slice(3))):a.addEventListener.apply(a,f.slice(2))};g.qa=function(b){for(var a=this.sa,c=0;c<a.length;c++){var d=a[c][0];if(!b||b==d){var e=a.splice(c--,1).pop(),f=e.splice(0,2).pop();0>d?(f=f[e.shift()],f.removeListener.apply(f,
e)):f.removeEventListener.apply(f,e)}}};g.Na=function(b){if(!b){var a=!0;b=0;var c;document.getElementsByTagName(this.fa).length&&this.B();for(var d of document.getElementsByTagName("script")){if(c=this.A.exec(d.src)){b|=1;var e=d.src;this.h[c[1]]&&(a=!1)}else if(c=this.ea.exec(d.innerText)){if(b|=2,this.h[c[1]]){a={};var f=[37,1,2,a];a[118]=parseInt(c[1],10);this.a.postMessage(f);a=!1}}else!d.src&&this.aa.test(d.innerText)&&(b|=4,this.B(),f=[34,!0,this.i(),null,d.outerHTML],this.a.postMessage(f));
if(7==b)break}e&&a&&(d=new XMLHttpRequest,d.responseType="text",d.timeout=1E4,d.onreadystatechange=this.ab.bind(this,e,d),d.open("GET",e,!0),d.send())}};g.ab=function(b,a){if(4==a.readyState){var c=this.A.exec(b);if((b=(b=this.ba.exec(a.response))&&parseInt(b[1]||b[2],10))&&(!this.h[b]||!this.h[c[1]])){var d=this.ca.exec(a.response);a=this.da.exec(a.response);if(d&&a&&d[2]==a[1]){c=c&&c[1];var e={};e[118]=b;e[119]=d[0];e[120]=a[0];e[124]=c;this.a.postMessage([37,1,1,e])}}}};g.La=function d(a,c){if(a)c&&
a.shift().disconnect(),this.C.disconnect(),this.ma.disconnect(),this.la.clear(),this.D.clear();else{this.B();c=0;for(var e of document.getElementsByTagName("script"))if(!e.src&&this.Y.test(e.innerText)){var f=this.i();this.a.postMessage([34,!0,f,c,e.outerHTML]);c+=e.outerHTML.length}c&&this.a.postMessage([34,!0]);this.C=new MutationObserver(this.Aa.bind(this));this.ma=new MutationObserver(this.za.bind(this));this.la=new Set;this.D=new Set}if(e=this.wa=document.querySelector(this.V)){if(a=this.C,a.observe(e,
{childList:!0}),!this.ha(e,!0)&&(e=e.querySelector(this.W)))(c=A(e,this.u))&&a.observe(e,{childList:!0}),a.observe(c||e.parentNode,{childList:!0})}else!a&&(e=document.querySelector(this.T))&&(c=new MutationObserver(d.bind(this,a=[])),a.push(c),c.observe(e,{childList:!0}))};g.ha=function(a,c){var d=this.C,e=this.u,f=this.S,m=this.ma,l=this.la,n=0,h;for(h of a.querySelectorAll(f))l.has(h)||h.querySelector(f)||(l.add(h),m.observe(h,{childList:!0,subtree:!0}),c&&(a=A(h,e))&&(d.observe(a,{childList:!0}),
n++),x(h.getElementsByTagName("video"),this.F.bind(this)));return n};g.Aa=function(a){var c=this.wa,d;for(d of a){a=c.isSameNode(d.target);for(var e of d.addedNodes)1==e.nodeType&&this.ha(e,a)}};g.za=function(a){var c=this.D,d=this.v,e;for(e of a)for(var f of e.addedNodes)if(1==f.nodeType)if(a=f.getElementsByTagName("video"),a.length)x(a,this.F.bind(this));else for(var m of c){a=m;for(var l=d;a&&l--;a=a.parentNode);a&&a.contains(f)&&this.F(m)}};g.F=function(a){if(!a.hasAttribute("__idm_id__")){var c=
this.D,d=this.v,e,f;for(e=a.parentNode;e&&d--;e=e.parentNode){var m=e;if("a"==e.firstChild.localName){var l=e.firstChild;break}var n=e.previousSibling;if(n&&"div"==n.localName){(f=e.getElementsByTagName("a")).length?l=f[0]:(f=n.getElementsByTagName("a")).length&&(l=f[f.length-1]);break}}l?l=l.href:A(a,this.U)?l=location.href:m&&1==(f=m.querySelectorAll(this.X)).length&&(l=f[0].href);l?(c.delete(a),a.setAttribute("__idm_link__",l),c=this.o(a),d=this.m(a),this.ka.observe(a,{attributes:!0,attributeFilter:["style"]}),
this.a.postMessage([41,c,a.localName,a.src||a.data,l,d])):c.add(a)}};g.Ma=function(a){if(!a)for(var c of document.getElementsByTagName("script"))if(!c.src&&this.$.test(c.innerText)){a=this.i();this.a.postMessage([34,!0,a,null,c.outerHTML]);break}};function A(a,c){var d;for(d=0;"<"==c[d];d++);for(a=a.closest(c.slice(d));a&&d--;a=a.parentNode);return a}function L(a,c){c&&(a[c]=!0);return a}new D}!0;
